### ISSUE TITLE
Question about dataset download

### ISSUE THREAD

**Issue by qiqiApink** [OpenGVLab/LORIS#4]
I want to download your dataset. But I got the following error when loading the dataset from huggingface.
`zipfile.BadZipFile: zipfiles that span multiple disks are not supported`
Can you help me fix this or are there other methods to access this dataset?

**Comment by JustinYuu** [comment]
Hi, you can try the command `git lfs clone https://huggingface.co/datasets/OpenGVLab/LORIS` to download the dataset to your local environment through the terminal.
